name: Integration tests

on: [push, pull_request]

env:
  GITHUB_ACTIONS: true

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        entry:
          - { cluster: 'opendistro', version: '1.13.3', secured: 'true' }
          - { cluster: 'opendistro', version: '1.13.3', secured: 'false' }
          - { cluster: 'opensearch', version: '1.2.4', secured: 'true' }
          - { cluster: 'opensearch', version: '1.2.4', secured: 'false' }
          - { cluster: 'opensearch', version: '1.3.1', secured: 'true' }
          - { cluster: 'opensearch', version: '1.3.1', secured: 'false' }
          - { cluster: 'opensearch', version: '1.2.4', secured: 'true' }
          - { cluster: 'opensearch', version: '1.2.4', secured: 'false' }
          - { cluster: 'opensearch', version: '1.1.0', secured: 'true' }
          - { cluster: 'opensearch', version: '1.1.0', secured: 'false' }

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Increase system limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Integ ${{ matrix.entry.cluster }} ${{ matrix.entry.version }} secured=${{ matrix.entry.secured }}
        run: "./.ci/run-tests ${{ matrix.entry.cluster }} ${{ matrix.entry.version }} ${{ matrix.entry.secured }}"
        