name: Integration Tests

on: [push, pull_request]

env:
  GITHUB_ACTIONS: true

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry:
          - { version: '1.1.0' }
          - { version: '1.2.4' }
          - { version: '1.3.4' }
          - { version: '2.2.0' }
          - { version: '2.4.0' }
        secured: ["true", "false"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Increase system limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt, clippy
      - name: Integ OpenSearch ${{ matrix.entry.version }} secured=${{ matrix.secured }}
        run: "./.ci/run-tests opensearch ${{ matrix.entry.version }} ${{ matrix.secured }}"
      - uses: codecov/codecov-action@v3
        with:
          files: ./test_results/opensearch.lcov
          flags: integration
        